
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_7sH1KZ-7CbihFkmZj2cfwAT1HHyOcc',
    iosBundleId: 'com.act4',
    appId: '1:1050858107779:ios:ed17e662b7b1c971f93cb6',
    storageBucket: 'act4-1b100.appspot.com',
    messagingSenderId: '1050858107779',
    iosClientId: 'undefined',
    projectId: 'act4-1b100'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwtSQtxrwlxVWmuR_y6pNx8YZwMJylkY',
    appId: '1:1050858107779:android:0b0b71ea286327fdf93cb6',
    messagingSenderId: '1050858107779',
    projectId: 'act4-1b100',
    storageBucket: 'act4-1b100.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpq2gMU26Sz46trDLzhmszmI3FAw3JQfM',
    authDomain: 'act4-1b100.firebaseapp.com',
    projectId: 'act4-1b100',
    storageBucket: 'act4-1b100.appspot.com',
    messagingSenderId: '1050858107779',
    appId: '1:1050858107779:web:0ccb72ad7cc23fc6f93cb6'
  );
}
